### ISSUE TITLE
大佬logger报错

### ISSUE THREAD

**Issue by buse88** [flyfishes/ctyun_keepalive#1]
line 14, in <module>
    __g_logger = logger.Logger()
                 ^^^^^^^^^^^^^
AttributeError: module 'logger' has no attribute 'Logger'. Did you mean: 'logger'?

根据百度提示先弄了import logging,然后再配置了 又会有新的错误都是跟这个__g_logger = logging.getLogger有关

**Comment by flyfishes** [comment]
sorry，漏了logger.py文件，已经补上。
