### ISSUE TITLE
大佬好,获取不到验证码

### ISSUE THREAD

**Issue by Steve5wutongyu6** [flyfishes/ctyun_keepalive#4]
大佬好,我这里配置完成后一直无法获取验证码.
直接使用 python ctyun-alive.py 命令运行会出现如下报错
![image](https://github.com/flyfishes/ctyun_keepalive/assets/77491648/14ce39c9-af60-4a06-8c8a-16493a96ac03)
在Pycharm中用运行按钮运行可以成功启动并显示web页面,但是验证码出不来

![image](https://github.com/flyfishes/ctyun_keepalive/assets/77491648/387e79da-f1e5-419c-b2b8-f3219b77a0ac)
![image](https://github.com/flyfishes/ctyun_keepalive/assets/77491648/aa6f25bc-b725-4ca2-951a-a674f7a49bc2)

**Comment by Steve5wutongyu6** [comment]
{
"account":"173******14",
"password":"********",
"browserType":"chrome",
"browserPath":"./chromedriver.exe",
"listenport":8000,
"listen_url":"0.0.0.0",
"push_token":"IYUU**********************************************d"
}

**Comment by flyfishes** [comment]
你可以直接打开static文件夹下面的ctyun.png文件，或者访问http://192.168.1.44:8000/static/ctyun.png看看

**Comment by Steve5wutongyu6** [comment]
您好,static下除了readme没有其他文件
![image](https://github.com/flyfishes/ctyun_keepalive/assets/77491648/e2d0aeb6-09f3-49d2-86f6-63e4f3473334)

**Comment by Steve5wutongyu6** [comment]
好的,已经解决,感谢😀
